#![allow(warnings)]
#[cfg(feature = "AOZArrangement")]
pub mod AOZArrangement;
#[cfg(feature = "AOZBoss")]
pub mod AOZBoss;
#[cfg(feature = "AOZContent")]
pub mod AOZContent;
#[cfg(feature = "AOZContentBriefingBNpc")]
pub mod AOZContentBriefingBNpc;
#[cfg(feature = "AOZContentBriefingObject")]
pub mod AOZContentBriefingObject;
#[cfg(feature = "AOZReport")]
pub mod AOZReport;
#[cfg(feature = "AOZReportReward")]
pub mod AOZReportReward;
#[cfg(feature = "AOZScore")]
pub mod AOZScore;
#[cfg(feature = "AOZWeeklyReward")]
pub mod AOZWeeklyReward;
#[cfg(feature = "Achievement")]
pub mod Achievement;
#[cfg(feature = "AchievementCategory")]
pub mod AchievementCategory;
#[cfg(feature = "AchievementHideCondition")]
pub mod AchievementHideCondition;
#[cfg(feature = "AchievementKind")]
pub mod AchievementKind;
#[cfg(feature = "AchievementTarget")]
pub mod AchievementTarget;
#[cfg(feature = "Action")]
pub mod Action;
#[cfg(feature = "ActionCastTimeline")]
pub mod ActionCastTimeline;
#[cfg(feature = "ActionCastVFX")]
pub mod ActionCastVFX;
#[cfg(feature = "ActionCategory")]
pub mod ActionCategory;
#[cfg(feature = "ActionComboRoute")]
pub mod ActionComboRoute;
#[cfg(feature = "ActionComboRouteTransient")]
pub mod ActionComboRouteTransient;
#[cfg(feature = "ActionCostType")]
pub mod ActionCostType;
#[cfg(feature = "ActionIndirection")]
pub mod ActionIndirection;
#[cfg(feature = "ActionInit")]
pub mod ActionInit;
#[cfg(feature = "ActionParam")]
pub mod ActionParam;
#[cfg(feature = "ActionProcStatus")]
pub mod ActionProcStatus;
#[cfg(feature = "ActionSetting")]
pub mod ActionSetting;
#[cfg(feature = "ActionTimeline")]
pub mod ActionTimeline;
#[cfg(feature = "ActionTimelineMove")]
pub mod ActionTimelineMove;
#[cfg(feature = "ActionTimelineReplace")]
pub mod ActionTimelineReplace;
#[cfg(feature = "ActionTransient")]
pub mod ActionTransient;
#[cfg(feature = "ActivityFeedButtons")]
pub mod ActivityFeedButtons;
#[cfg(feature = "ActivityFeedCaptions")]
pub mod ActivityFeedCaptions;
#[cfg(feature = "ActivityFeedGroupCaptions")]
pub mod ActivityFeedGroupCaptions;
#[cfg(feature = "ActivityFeedImages")]
pub mod ActivityFeedImages;
#[cfg(feature = "Addon")]
pub mod Addon;
#[cfg(feature = "AddonHudSize")]
pub mod AddonHudSize;
#[cfg(feature = "AddonLayout")]
pub mod AddonLayout;
#[cfg(feature = "AddonParam")]
pub mod AddonParam;
#[cfg(feature = "AddonTalkParam")]
pub mod AddonTalkParam;
#[cfg(feature = "AddonTransient")]
pub mod AddonTransient;
#[cfg(feature = "AdvancedVibration")]
pub mod AdvancedVibration;
#[cfg(feature = "Adventure")]
pub mod Adventure;
#[cfg(feature = "AdventureExPhase")]
pub mod AdventureExPhase;
#[cfg(feature = "AetherCurrent")]
pub mod AetherCurrent;
#[cfg(feature = "AetherCurrentCompFlgSet")]
pub mod AetherCurrentCompFlgSet;
#[cfg(feature = "AetherialWheel")]
pub mod AetherialWheel;
#[cfg(feature = "Aetheryte")]
pub mod Aetheryte;
#[cfg(feature = "AetheryteSystemDefine")]
pub mod AetheryteSystemDefine;
#[cfg(feature = "AetheryteTransient")]
pub mod AetheryteTransient;
#[cfg(feature = "AirshipExplorationLevel")]
pub mod AirshipExplorationLevel;
#[cfg(feature = "AirshipExplorationLog")]
pub mod AirshipExplorationLog;
#[cfg(feature = "AirshipExplorationParamType")]
pub mod AirshipExplorationParamType;
#[cfg(feature = "AirshipExplorationPart")]
pub mod AirshipExplorationPart;
#[cfg(feature = "AirshipExplorationPoint")]
pub mod AirshipExplorationPoint;
#[cfg(feature = "AirshipSkyIsland")]
pub mod AirshipSkyIsland;
#[cfg(feature = "AkatsukiNote")]
pub mod AkatsukiNote;
#[cfg(feature = "AkatsukiNoteString")]
pub mod AkatsukiNoteString;
#[cfg(feature = "AnimaWeapon5")]
pub mod AnimaWeapon5;
#[cfg(feature = "AnimaWeapon5Param")]
pub mod AnimaWeapon5Param;
#[cfg(feature = "AnimaWeapon5PatternGroup")]
pub mod AnimaWeapon5PatternGroup;
#[cfg(feature = "AnimaWeapon5SpiritTalk")]
pub mod AnimaWeapon5SpiritTalk;
#[cfg(feature = "AnimaWeapon5SpiritTalkParam")]
pub mod AnimaWeapon5SpiritTalkParam;
#[cfg(feature = "AnimaWeapon5SpiritTalkType")]
pub mod AnimaWeapon5SpiritTalkType;
#[cfg(feature = "AnimaWeapon5TradeItem")]
pub mod AnimaWeapon5TradeItem;
#[cfg(feature = "AnimaWeaponFUITalk")]
pub mod AnimaWeaponFUITalk;
#[cfg(feature = "AnimaWeaponFUITalkParam")]
pub mod AnimaWeaponFUITalkParam;
#[cfg(feature = "AnimaWeaponIcon")]
pub mod AnimaWeaponIcon;
#[cfg(feature = "AnimaWeaponItem")]
pub mod AnimaWeaponItem;
#[cfg(feature = "AnimationLOD")]
pub mod AnimationLOD;
#[cfg(feature = "AozAction")]
pub mod AozAction;
#[cfg(feature = "AozActionTransient")]
pub mod AozActionTransient;
#[cfg(feature = "AquariumFish")]
pub mod AquariumFish;
#[cfg(feature = "AquariumWater")]
pub mod AquariumWater;
#[cfg(feature = "ArchiveItem")]
pub mod ArchiveItem;
#[cfg(feature = "ArrayEventHandler")]
pub mod ArrayEventHandler;
#[cfg(feature = "AttackType")]
pub mod AttackType;
#[cfg(feature = "Attract")]
pub mod Attract;
#[cfg(feature = "Attributive")]
pub mod Attributive;
#[cfg(feature = "BGM")]
pub mod BGM;
#[cfg(feature = "BGMFade")]
pub mod BGMFade;
#[cfg(feature = "BGMFadeType")]
pub mod BGMFadeType;
#[cfg(feature = "BGMScene")]
pub mod BGMScene;
#[cfg(feature = "BGMSituation")]
pub mod BGMSituation;
#[cfg(feature = "BGMSwitch")]
pub mod BGMSwitch;
#[cfg(feature = "BGMSystemDefine")]
pub mod BGMSystemDefine;
#[cfg(feature = "BNpcAnnounceIcon")]
pub mod BNpcAnnounceIcon;
#[cfg(feature = "BNpcBase")]
pub mod BNpcBase;
#[cfg(feature = "BNpcBasePopVfx")]
pub mod BNpcBasePopVfx;
#[cfg(feature = "BNpcCustomize")]
pub mod BNpcCustomize;
#[cfg(feature = "BNpcName")]
pub mod BNpcName;
#[cfg(feature = "BNpcParts")]
pub mod BNpcParts;
#[cfg(feature = "BNpcState")]
pub mod BNpcState;
#[cfg(feature = "BacklightColor")]
pub mod BacklightColor;
#[cfg(feature = "Ballista")]
pub mod Ballista;
#[cfg(feature = "Balloon")]
pub mod Balloon;
#[cfg(feature = "BankaCraftWorks")]
pub mod BankaCraftWorks;
#[cfg(feature = "BankaCraftWorksSupply")]
pub mod BankaCraftWorksSupply;
#[cfg(feature = "BannerBg")]
pub mod BannerBg;
#[cfg(feature = "BannerCondition")]
pub mod BannerCondition;
#[cfg(feature = "BannerDecoration")]
pub mod BannerDecoration;
#[cfg(feature = "BannerDesignPreset")]
pub mod BannerDesignPreset;
#[cfg(feature = "BannerFacial")]
pub mod BannerFacial;
#[cfg(feature = "BannerFrame")]
pub mod BannerFrame;
#[cfg(feature = "BannerObtainHintType")]
pub mod BannerObtainHintType;
#[cfg(feature = "BannerPreset")]
pub mod BannerPreset;
#[cfg(feature = "BannerTimeline")]
pub mod BannerTimeline;
#[cfg(feature = "BaseParam")]
pub mod BaseParam;
#[cfg(feature = "Battalion")]
pub mod Battalion;
#[cfg(feature = "BattleLeve")]
pub mod BattleLeve;
#[cfg(feature = "BattleLeveRule")]
pub mod BattleLeveRule;
#[cfg(feature = "BeastRankBonus")]
pub mod BeastRankBonus;
#[cfg(feature = "BeastReputationRank")]
pub mod BeastReputationRank;
#[cfg(feature = "BeastTribe")]
pub mod BeastTribe;
#[cfg(feature = "Behavior")]
pub mod Behavior;
#[cfg(feature = "BehaviorMove")]
pub mod BehaviorMove;
#[cfg(feature = "BehaviorPath")]
pub mod BehaviorPath;
#[cfg(feature = "BenchmarkCutSceneTable")]
pub mod BenchmarkCutSceneTable;
#[cfg(feature = "BenchmarkOverrideEquipment")]
pub mod BenchmarkOverrideEquipment;
#[cfg(feature = "BgcArmyAction")]
pub mod BgcArmyAction;
#[cfg(feature = "BgcArmyActionTransient")]
pub mod BgcArmyActionTransient;
#[cfg(feature = "Booster")]
pub mod Booster;
#[cfg(feature = "Buddy")]
pub mod Buddy;
#[cfg(feature = "BuddyAction")]
pub mod BuddyAction;
#[cfg(feature = "BuddyEquip")]
pub mod BuddyEquip;
#[cfg(feature = "BuddyItem")]
pub mod BuddyItem;
#[cfg(feature = "BuddyRank")]
pub mod BuddyRank;
#[cfg(feature = "BuddySkill")]
pub mod BuddySkill;
#[cfg(feature = "CSBonusContent")]
pub mod CSBonusContent;
#[cfg(feature = "CSBonusContentIdentifier")]
pub mod CSBonusContentIdentifier;
#[cfg(feature = "CSBonusContentType")]
pub mod CSBonusContentType;
#[cfg(feature = "CSBonusMission")]
pub mod CSBonusMission;
#[cfg(feature = "CSBonusMissionType")]
pub mod CSBonusMissionType;
#[cfg(feature = "CSBonusSeason")]
pub mod CSBonusSeason;
#[cfg(feature = "CSBonusTextData")]
pub mod CSBonusTextData;
#[cfg(feature = "Cabinet")]
pub mod Cabinet;
#[cfg(feature = "CabinetCategory")]
pub mod CabinetCategory;
#[cfg(feature = "CabinetSubCategory")]
pub mod CabinetSubCategory;
#[cfg(feature = "Calendar")]
pub mod Calendar;
#[cfg(feature = "Carry")]
pub mod Carry;
#[cfg(feature = "Channeling")]
pub mod Channeling;
#[cfg(feature = "CharaCardBase")]
pub mod CharaCardBase;
#[cfg(feature = "CharaCardDecoration")]
pub mod CharaCardDecoration;
#[cfg(feature = "CharaCardDesignCategory")]
pub mod CharaCardDesignCategory;
#[cfg(feature = "CharaCardDesignPreset")]
pub mod CharaCardDesignPreset;
#[cfg(feature = "CharaCardDesignType")]
pub mod CharaCardDesignType;
#[cfg(feature = "CharaCardHeader")]
pub mod CharaCardHeader;
#[cfg(feature = "CharaCardPlayStyle")]
pub mod CharaCardPlayStyle;
#[cfg(feature = "CharaMakeClassEquip")]
pub mod CharaMakeClassEquip;
#[cfg(feature = "CharaMakeCustomize")]
pub mod CharaMakeCustomize;
#[cfg(feature = "CharaMakeName")]
pub mod CharaMakeName;
#[cfg(feature = "CharaMakeType")]
pub mod CharaMakeType;
#[cfg(feature = "ChocoboRace")]
pub mod ChocoboRace;
#[cfg(feature = "ChocoboRaceAbility")]
pub mod ChocoboRaceAbility;
#[cfg(feature = "ChocoboRaceAbilityType")]
pub mod ChocoboRaceAbilityType;
#[cfg(feature = "ChocoboRaceCalculateParam")]
pub mod ChocoboRaceCalculateParam;
#[cfg(feature = "ChocoboRaceChallenge")]
pub mod ChocoboRaceChallenge;
#[cfg(feature = "ChocoboRaceItem")]
pub mod ChocoboRaceItem;
#[cfg(feature = "ChocoboRaceRank")]
pub mod ChocoboRaceRank;
#[cfg(feature = "ChocoboRaceRanking")]
pub mod ChocoboRaceRanking;
#[cfg(feature = "ChocoboRaceStatus")]
pub mod ChocoboRaceStatus;
#[cfg(feature = "ChocoboRaceTerritory")]
pub mod ChocoboRaceTerritory;
#[cfg(feature = "ChocoboRaceTutorial")]
pub mod ChocoboRaceTutorial;
#[cfg(feature = "ChocoboRaceWeather")]
pub mod ChocoboRaceWeather;
#[cfg(feature = "ChocoboTaxi")]
pub mod ChocoboTaxi;
#[cfg(feature = "ChocoboTaxiStand")]
pub mod ChocoboTaxiStand;
#[cfg(feature = "CircleActivity")]
pub mod CircleActivity;
#[cfg(feature = "ClassJob")]
pub mod ClassJob;
#[cfg(feature = "ClassJobActionUI")]
pub mod ClassJobActionUI;
#[cfg(feature = "ClassJobActionUICategory")]
pub mod ClassJobActionUICategory;
#[cfg(feature = "ClassJobCategory")]
pub mod ClassJobCategory;
#[cfg(feature = "ClassJobResident")]
pub mod ClassJobResident;
#[cfg(feature = "CollectablesRefine")]
pub mod CollectablesRefine;
#[cfg(feature = "CollectablesShop")]
pub mod CollectablesShop;
#[cfg(feature = "CollectablesShopItem")]
pub mod CollectablesShopItem;
#[cfg(feature = "CollectablesShopItemGroup")]
pub mod CollectablesShopItemGroup;
#[cfg(feature = "CollectablesShopRefine")]
pub mod CollectablesShopRefine;
#[cfg(feature = "CollectablesShopRewardItem")]
pub mod CollectablesShopRewardItem;
#[cfg(feature = "CollectablesShopRewardScrip")]
pub mod CollectablesShopRewardScrip;
#[cfg(feature = "CollisionIdPallet")]
pub mod CollisionIdPallet;
#[cfg(feature = "ColorFilter")]
pub mod ColorFilter;
#[cfg(feature = "Colosseum")]
pub mod Colosseum;
#[cfg(feature = "ColosseumMatchRank")]
pub mod ColosseumMatchRank;
#[cfg(feature = "Companion")]
pub mod Companion;
#[cfg(feature = "CompanionMove")]
pub mod CompanionMove;
#[cfg(feature = "CompanionTransient")]
pub mod CompanionTransient;
#[cfg(feature = "CompanyAction")]
pub mod CompanyAction;
#[cfg(feature = "CompanyCraftDraft")]
pub mod CompanyCraftDraft;
#[cfg(feature = "CompanyCraftDraftCategory")]
pub mod CompanyCraftDraftCategory;
#[cfg(feature = "CompanyCraftManufactoryState")]
pub mod CompanyCraftManufactoryState;
#[cfg(feature = "CompanyCraftPart")]
pub mod CompanyCraftPart;
#[cfg(feature = "CompanyCraftProcess")]
pub mod CompanyCraftProcess;
#[cfg(feature = "CompanyCraftSequence")]
pub mod CompanyCraftSequence;
#[cfg(feature = "CompanyCraftSupplyItem")]
pub mod CompanyCraftSupplyItem;
#[cfg(feature = "CompanyCraftType")]
pub mod CompanyCraftType;
#[cfg(feature = "CompanyLeve")]
pub mod CompanyLeve;
#[cfg(feature = "CompanyLeveRule")]
pub mod CompanyLeveRule;
#[cfg(feature = "CompleteJournal")]
pub mod CompleteJournal;
#[cfg(feature = "CompleteJournalCategory")]
pub mod CompleteJournalCategory;
#[cfg(feature = "Completion")]
pub mod Completion;
#[cfg(feature = "Condition")]
pub mod Condition;
#[cfg(feature = "ConfigKey")]
pub mod ConfigKey;
#[cfg(feature = "ContentAttributeRect")]
pub mod ContentAttributeRect;
#[cfg(feature = "ContentCloseCycle")]
pub mod ContentCloseCycle;
#[cfg(feature = "ContentDirectorBattleTalk")]
pub mod ContentDirectorBattleTalk;
#[cfg(feature = "ContentDirectorManagedSG")]
pub mod ContentDirectorManagedSG;
#[cfg(feature = "ContentEffectiveTime")]
pub mod ContentEffectiveTime;
#[cfg(feature = "ContentEntry")]
pub mod ContentEntry;
#[cfg(feature = "ContentEventItem")]
pub mod ContentEventItem;
#[cfg(feature = "ContentExAction")]
pub mod ContentExAction;
#[cfg(feature = "ContentFinderCondition")]
pub mod ContentFinderCondition;
#[cfg(feature = "ContentFinderConditionTransient")]
pub mod ContentFinderConditionTransient;
#[cfg(feature = "ContentGauge")]
pub mod ContentGauge;
#[cfg(feature = "ContentGaugeColor")]
pub mod ContentGaugeColor;
#[cfg(feature = "ContentMemberType")]
pub mod ContentMemberType;
#[cfg(feature = "ContentNpc")]
pub mod ContentNpc;
#[cfg(feature = "ContentNpcTalk")]
pub mod ContentNpcTalk;
#[cfg(feature = "ContentRandomSelect")]
pub mod ContentRandomSelect;
#[cfg(feature = "ContentRewardCondition")]
pub mod ContentRewardCondition;
#[cfg(feature = "ContentRoulette")]
pub mod ContentRoulette;
#[cfg(feature = "ContentRouletteOpenRule")]
pub mod ContentRouletteOpenRule;
#[cfg(feature = "ContentRouletteRoleBonus")]
pub mod ContentRouletteRoleBonus;
#[cfg(feature = "ContentTalk")]
pub mod ContentTalk;
#[cfg(feature = "ContentTalkParam")]
pub mod ContentTalkParam;
#[cfg(feature = "ContentTodo")]
pub mod ContentTodo;
#[cfg(feature = "ContentTourismConstruct")]
pub mod ContentTourismConstruct;
#[cfg(feature = "ContentType")]
pub mod ContentType;
#[cfg(feature = "ContentUICategory")]
pub mod ContentUICategory;
#[cfg(feature = "ContentsNote")]
pub mod ContentsNote;
#[cfg(feature = "ContentsNoteCategory")]
pub mod ContentsNoteCategory;
#[cfg(feature = "ContentsNoteLevel")]
pub mod ContentsNoteLevel;
#[cfg(feature = "ContentsNoteRewardEurekaEXP")]
pub mod ContentsNoteRewardEurekaEXP;
#[cfg(feature = "ContentsTutorial")]
pub mod ContentsTutorial;
#[cfg(feature = "ContentsTutorialPage")]
pub mod ContentsTutorialPage;
#[cfg(feature = "CraftAction")]
pub mod CraftAction;
#[cfg(feature = "CraftActionIndirection")]
pub mod CraftActionIndirection;
#[cfg(feature = "CraftLeve")]
pub mod CraftLeve;
#[cfg(feature = "CraftLeveTalk")]
pub mod CraftLeveTalk;
#[cfg(feature = "CraftType")]
pub mod CraftType;
#[cfg(feature = "Credit")]
pub mod Credit;
#[cfg(feature = "CreditBackImage")]
pub mod CreditBackImage;
#[cfg(feature = "CreditCast")]
pub mod CreditCast;
#[cfg(feature = "CreditDataSet")]
pub mod CreditDataSet;
#[cfg(feature = "CreditFont")]
pub mod CreditFont;
#[cfg(feature = "CreditList")]
pub mod CreditList;
#[cfg(feature = "CreditListText")]
pub mod CreditListText;
#[cfg(feature = "CreditVersion")]
pub mod CreditVersion;
#[cfg(feature = "CurrencyScripConvert")]
pub mod CurrencyScripConvert;
#[cfg(feature = "CustomTalk")]
pub mod CustomTalk;
#[cfg(feature = "CustomTalkDefineClient")]
pub mod CustomTalkDefineClient;
#[cfg(feature = "CustomTalkNestHandlers")]
pub mod CustomTalkNestHandlers;
#[cfg(feature = "CustomTalkResident")]
pub mod CustomTalkResident;
#[cfg(feature = "CutActionTimeline")]
pub mod CutActionTimeline;
#[cfg(feature = "CutSceneIncompQuest")]
pub mod CutSceneIncompQuest;
#[cfg(feature = "CutScreenImage")]
pub mod CutScreenImage;
#[cfg(feature = "Cutscene")]
pub mod Cutscene;
#[cfg(feature = "CutsceneActorSize")]
pub mod CutsceneActorSize;
#[cfg(feature = "CutsceneEventMotion")]
pub mod CutsceneEventMotion;
#[cfg(feature = "CutsceneMotion")]
pub mod CutsceneMotion;
#[cfg(feature = "CutsceneName")]
pub mod CutsceneName;
#[cfg(feature = "CutsceneWorkIndex")]
pub mod CutsceneWorkIndex;
#[cfg(feature = "CycleTime")]
pub mod CycleTime;
#[cfg(feature = "DailySupplyItem")]
pub mod DailySupplyItem;
#[cfg(feature = "DawnContent")]
pub mod DawnContent;
#[cfg(feature = "DawnContentParticipable")]
pub mod DawnContentParticipable;
#[cfg(feature = "DawnGrowMember")]
pub mod DawnGrowMember;
#[cfg(feature = "DawnMember")]
pub mod DawnMember;
#[cfg(feature = "DawnMemberUIParam")]
pub mod DawnMemberUIParam;
#[cfg(feature = "DawnQuestMember")]
pub mod DawnQuestMember;
#[cfg(feature = "DeepDungeon")]
pub mod DeepDungeon;
#[cfg(feature = "DeepDungeonBan")]
pub mod DeepDungeonBan;
#[cfg(feature = "DeepDungeonDanger")]
pub mod DeepDungeonDanger;
#[cfg(feature = "DeepDungeonDemiclone")]
pub mod DeepDungeonDemiclone;
#[cfg(feature = "DeepDungeonEquipment")]
pub mod DeepDungeonEquipment;
#[cfg(feature = "DeepDungeonFloorEffectUI")]
pub mod DeepDungeonFloorEffectUI;
#[cfg(feature = "DeepDungeonGrowData")]
pub mod DeepDungeonGrowData;
#[cfg(feature = "DeepDungeonItem")]
pub mod DeepDungeonItem;
#[cfg(feature = "DeepDungeonLayer")]
pub mod DeepDungeonLayer;
#[cfg(feature = "DeepDungeonMagicStone")]
pub mod DeepDungeonMagicStone;
#[cfg(feature = "DeepDungeonMap5X")]
pub mod DeepDungeonMap5X;
#[cfg(feature = "DeepDungeonRoom")]
pub mod DeepDungeonRoom;
#[cfg(feature = "DeepDungeonStatus")]
pub mod DeepDungeonStatus;
#[cfg(feature = "DefaultTalk")]
pub mod DefaultTalk;
#[cfg(feature = "DefaultTalkLipSyncType")]
pub mod DefaultTalkLipSyncType;
#[cfg(feature = "DeliveryQuest")]
pub mod DeliveryQuest;
#[cfg(feature = "Description")]
pub mod Description;
#[cfg(feature = "DescriptionPage")]
pub mod DescriptionPage;
#[cfg(feature = "DescriptionSection")]
pub mod DescriptionSection;
#[cfg(feature = "DescriptionStandAlone")]
pub mod DescriptionStandAlone;
#[cfg(feature = "DescriptionStandAloneTransient")]
pub mod DescriptionStandAloneTransient;
#[cfg(feature = "DescriptionString")]
pub mod DescriptionString;
#[cfg(feature = "DirectorSystemDefine")]
pub mod DirectorSystemDefine;
#[cfg(feature = "DirectorType")]
pub mod DirectorType;
#[cfg(feature = "DisposalShop")]
pub mod DisposalShop;
#[cfg(feature = "DisposalShopFilterType")]
pub mod DisposalShopFilterType;
#[cfg(feature = "DisposalShopItem")]
pub mod DisposalShopItem;
#[cfg(feature = "DomaStoryProgress")]
pub mod DomaStoryProgress;
#[cfg(feature = "DpsChallenge")]
pub mod DpsChallenge;
#[cfg(feature = "DpsChallengeOfficer")]
pub mod DpsChallengeOfficer;
#[cfg(feature = "DpsChallengeTransient")]
pub mod DpsChallengeTransient;
#[cfg(feature = "DynamicEvent")]
pub mod DynamicEvent;
#[cfg(feature = "DynamicEventEnemyType")]
pub mod DynamicEventEnemyType;
#[cfg(feature = "DynamicEventManager")]
pub mod DynamicEventManager;
#[cfg(feature = "DynamicEventSet")]
pub mod DynamicEventSet;
#[cfg(feature = "DynamicEventSingleBattle")]
pub mod DynamicEventSingleBattle;
#[cfg(feature = "DynamicEventType")]
pub mod DynamicEventType;
#[cfg(feature = "DynamicEventUIType")]
pub mod DynamicEventUIType;
#[cfg(feature = "ENpcBase")]
pub mod ENpcBase;
#[cfg(feature = "ENpcDressUp")]
pub mod ENpcDressUp;
#[cfg(feature = "ENpcDressUpDress")]
pub mod ENpcDressUpDress;
#[cfg(feature = "ENpcResident")]
pub mod ENpcResident;
#[cfg(feature = "EObj")]
pub mod EObj;
#[cfg(feature = "EObjName")]
pub mod EObjName;
#[cfg(feature = "EmjAddon")]
pub mod EmjAddon;
#[cfg(feature = "EmjCharaViewCamera")]
pub mod EmjCharaViewCamera;
#[cfg(feature = "EmjCostume")]
pub mod EmjCostume;
#[cfg(feature = "EmjCostumeData")]
pub mod EmjCostumeData;
#[cfg(feature = "EmjDani")]
pub mod EmjDani;
#[cfg(feature = "EmjVoiceNpc")]
pub mod EmjVoiceNpc;
#[cfg(feature = "Emote")]
pub mod Emote;
#[cfg(feature = "EmoteCategory")]
pub mod EmoteCategory;
#[cfg(feature = "EmoteMode")]
pub mod EmoteMode;
#[cfg(feature = "EmoteTransient")]
pub mod EmoteTransient;
#[cfg(feature = "EquipRaceCategory")]
pub mod EquipRaceCategory;
#[cfg(feature = "EquipSlotCategory")]
pub mod EquipSlotCategory;
#[cfg(feature = "Error")]
pub mod Error;
#[cfg(feature = "Eureka")]
pub mod Eureka;
#[cfg(feature = "EurekaAetherItem")]
pub mod EurekaAetherItem;
#[cfg(feature = "EurekaAethernet")]
pub mod EurekaAethernet;
#[cfg(feature = "EurekaDungeonPortal")]
pub mod EurekaDungeonPortal;
#[cfg(feature = "EurekaGrowData")]
pub mod EurekaGrowData;
#[cfg(feature = "EurekaLogosMixerProbability")]
pub mod EurekaLogosMixerProbability;
#[cfg(feature = "EurekaMagiaAction")]
pub mod EurekaMagiaAction;
#[cfg(feature = "EurekaMagiciteItem")]
pub mod EurekaMagiciteItem;
#[cfg(feature = "EurekaMagiciteItemType")]
pub mod EurekaMagiciteItemType;
#[cfg(feature = "EurekaSphereElementAdjust")]
pub mod EurekaSphereElementAdjust;
#[cfg(feature = "EurekaStoryProgress")]
pub mod EurekaStoryProgress;
#[cfg(feature = "EventAction")]
pub mod EventAction;
#[cfg(feature = "EventCustomIconType")]
pub mod EventCustomIconType;
#[cfg(feature = "EventExtraConditionSet")]
pub mod EventExtraConditionSet;
#[cfg(feature = "EventGimmickPathMove")]
pub mod EventGimmickPathMove;
#[cfg(feature = "EventIconPriority")]
pub mod EventIconPriority;
#[cfg(feature = "EventIconPriorityPair")]
pub mod EventIconPriorityPair;
#[cfg(feature = "EventIconType")]
pub mod EventIconType;
#[cfg(feature = "EventItem")]
pub mod EventItem;
#[cfg(feature = "EventItemCastTimeline")]
pub mod EventItemCastTimeline;
#[cfg(feature = "EventItemCategory")]
pub mod EventItemCategory;
#[cfg(feature = "EventItemHelp")]
pub mod EventItemHelp;
#[cfg(feature = "EventItemTimeline")]
pub mod EventItemTimeline;
#[cfg(feature = "EventMountGimmickPathMove")]
pub mod EventMountGimmickPathMove;
#[cfg(feature = "EventPathMove")]
pub mod EventPathMove;
#[cfg(feature = "EventSituationIconTooltip")]
pub mod EventSituationIconTooltip;
#[cfg(feature = "EventSystemDefine")]
pub mod EventSystemDefine;
#[cfg(feature = "EventVfx")]
pub mod EventVfx;
#[cfg(feature = "ExHotbarCrossbarIndexType")]
pub mod ExHotbarCrossbarIndexType;
#[cfg(feature = "ExVersion")]
pub mod ExVersion;
#[cfg(feature = "ExportedGatheringPoint")]
pub mod ExportedGatheringPoint;
#[cfg(feature = "ExportedSG")]
pub mod ExportedSG;
#[cfg(feature = "ExtraCommand")]
pub mod ExtraCommand;
#[cfg(feature = "FCActivity")]
pub mod FCActivity;
#[cfg(feature = "FCActivityCategory")]
pub mod FCActivityCategory;
#[cfg(feature = "FCAuthority")]
pub mod FCAuthority;
#[cfg(feature = "FCAuthorityCategory")]
pub mod FCAuthorityCategory;
#[cfg(feature = "FCChestName")]
pub mod FCChestName;
#[cfg(feature = "FCCrestSymbol")]
pub mod FCCrestSymbol;
#[cfg(feature = "FCDefine")]
pub mod FCDefine;
#[cfg(feature = "FCHierarchy")]
pub mod FCHierarchy;
#[cfg(feature = "FCProfile")]
pub mod FCProfile;
#[cfg(feature = "FCRank")]
pub mod FCRank;
#[cfg(feature = "FCReputation")]
pub mod FCReputation;
#[cfg(feature = "FCRights")]
pub mod FCRights;
#[cfg(feature = "FGSAddon")]
pub mod FGSAddon;
#[cfg(feature = "FGSStageUI")]
pub mod FGSStageUI;
#[cfg(feature = "FashionCheckThemeCategory")]
pub mod FashionCheckThemeCategory;
#[cfg(feature = "FashionCheckWeeklyTheme")]
pub mod FashionCheckWeeklyTheme;
#[cfg(feature = "Fate")]
pub mod Fate;
#[cfg(feature = "FateEvent")]
pub mod FateEvent;
#[cfg(feature = "FateMode")]
pub mod FateMode;
#[cfg(feature = "FateProgressUI")]
pub mod FateProgressUI;
#[cfg(feature = "FateRuleEx")]
pub mod FateRuleEx;
#[cfg(feature = "FateShop")]
pub mod FateShop;
#[cfg(feature = "FateTokenType")]
pub mod FateTokenType;
#[cfg(feature = "FccShop")]
pub mod FccShop;
#[cfg(feature = "Festival")]
pub mod Festival;
#[cfg(feature = "FieldMarker")]
pub mod FieldMarker;
#[cfg(feature = "FishParameter")]
pub mod FishParameter;
#[cfg(feature = "FishParameterReverse")]
pub mod FishParameterReverse;
#[cfg(feature = "FishingBaitParameter")]
pub mod FishingBaitParameter;
#[cfg(feature = "FishingNoteInfo")]
pub mod FishingNoteInfo;
#[cfg(feature = "FishingRecordType")]
pub mod FishingRecordType;
#[cfg(feature = "FishingRecordTypeTransient")]
pub mod FishingRecordTypeTransient;
#[cfg(feature = "FishingSpot")]
pub mod FishingSpot;
#[cfg(feature = "FittingShop")]
pub mod FittingShop;
#[cfg(feature = "FittingShopCategory")]
pub mod FittingShopCategory;
#[cfg(feature = "FittingShopCategoryItem")]
pub mod FittingShopCategoryItem;
#[cfg(feature = "FittingShopItemSet")]
pub mod FittingShopItemSet;
#[cfg(feature = "FollowMount")]
pub mod FollowMount;
#[cfg(feature = "Frontline")]
pub mod Frontline;
#[cfg(feature = "Frontline01")]
pub mod Frontline01;
#[cfg(feature = "Frontline02")]
pub mod Frontline02;
#[cfg(feature = "Frontline03")]
pub mod Frontline03;
#[cfg(feature = "FurnitureCatalogCategory")]
pub mod FurnitureCatalogCategory;
#[cfg(feature = "FurnitureCatalogItemList")]
pub mod FurnitureCatalogItemList;
#[cfg(feature = "GCRankGridaniaFemaleText")]
pub mod GCRankGridaniaFemaleText;
#[cfg(feature = "GCRankGridaniaMaleText")]
pub mod GCRankGridaniaMaleText;
#[cfg(feature = "GCRankLimsaFemaleText")]
pub mod GCRankLimsaFemaleText;
#[cfg(feature = "GCRankLimsaMaleText")]
pub mod GCRankLimsaMaleText;
#[cfg(feature = "GCRankUldahFemaleText")]
pub mod GCRankUldahFemaleText;
#[cfg(feature = "GCRankUldahMaleText")]
pub mod GCRankUldahMaleText;
#[cfg(feature = "GCScripShopCategory")]
pub mod GCScripShopCategory;
#[cfg(feature = "GCScripShopItem")]
pub mod GCScripShopItem;
#[cfg(feature = "GCShop")]
pub mod GCShop;
#[cfg(feature = "GCShopItemCategory")]
pub mod GCShopItemCategory;
#[cfg(feature = "GCSupplyDefine")]
pub mod GCSupplyDefine;
#[cfg(feature = "GCSupplyDuty")]
pub mod GCSupplyDuty;
#[cfg(feature = "GCSupplyDutyReward")]
pub mod GCSupplyDutyReward;
#[cfg(feature = "GFATE")]
pub mod GFATE;
#[cfg(feature = "GFateClimbing")]
pub mod GFateClimbing;
#[cfg(feature = "GFateClimbing2")]
pub mod GFateClimbing2;
#[cfg(feature = "GFateClimbing2Content")]
pub mod GFateClimbing2Content;
#[cfg(feature = "GFateClimbing2TotemType")]
pub mod GFateClimbing2TotemType;
#[cfg(feature = "GFateDance")]
pub mod GFateDance;
#[cfg(feature = "GFateHiddenObject")]
pub mod GFateHiddenObject;
#[cfg(feature = "GFateRideShooting")]
pub mod GFateRideShooting;
#[cfg(feature = "GFateRoulette")]
pub mod GFateRoulette;
#[cfg(feature = "GFateStelth")]
pub mod GFateStelth;
#[cfg(feature = "GFateType")]
pub mod GFateType;
#[cfg(feature = "GameRewardObtainType")]
pub mod GameRewardObtainType;
#[cfg(feature = "GardeningSeed")]
pub mod GardeningSeed;
#[cfg(feature = "GathererCrafterLvAdjustTable")]
pub mod GathererCrafterLvAdjustTable;
#[cfg(feature = "GathererCrafterTool")]
pub mod GathererCrafterTool;
#[cfg(feature = "GathererReductionReward")]
pub mod GathererReductionReward;
#[cfg(feature = "GatheringCondition")]
pub mod GatheringCondition;
#[cfg(feature = "GatheringExp")]
pub mod GatheringExp;
#[cfg(feature = "GatheringItem")]
pub mod GatheringItem;
#[cfg(feature = "GatheringItemLevelConvertTable")]
pub mod GatheringItemLevelConvertTable;
#[cfg(feature = "GatheringItemPoint")]
pub mod GatheringItemPoint;
#[cfg(feature = "GatheringLeve")]
pub mod GatheringLeve;
#[cfg(feature = "GatheringLeveBNpcEntry")]
pub mod GatheringLeveBNpcEntry;
#[cfg(feature = "GatheringLeveRoute")]
pub mod GatheringLeveRoute;
#[cfg(feature = "GatheringLeveRule")]
pub mod GatheringLeveRule;
#[cfg(feature = "GatheringNotebookItem")]
pub mod GatheringNotebookItem;
#[cfg(feature = "GatheringNotebookList")]
pub mod GatheringNotebookList;
#[cfg(feature = "GatheringPoint")]
pub mod GatheringPoint;
#[cfg(feature = "GatheringPointBase")]
pub mod GatheringPointBase;
#[cfg(feature = "GatheringPointBonus")]
pub mod GatheringPointBonus;
#[cfg(feature = "GatheringPointBonusType")]
pub mod GatheringPointBonusType;
#[cfg(feature = "GatheringPointName")]
pub mod GatheringPointName;
#[cfg(feature = "GatheringPointTransient")]
pub mod GatheringPointTransient;
#[cfg(feature = "GatheringRarePopTimeTable")]
pub mod GatheringRarePopTimeTable;
#[cfg(feature = "GatheringSubCategory")]
pub mod GatheringSubCategory;
#[cfg(feature = "GatheringType")]
pub mod GatheringType;
#[cfg(feature = "GcArmyCandidateCategory")]
pub mod GcArmyCandidateCategory;
#[cfg(feature = "GcArmyCapture")]
pub mod GcArmyCapture;
#[cfg(feature = "GcArmyCaptureTactics")]
pub mod GcArmyCaptureTactics;
#[cfg(feature = "GcArmyEquipPreset")]
pub mod GcArmyEquipPreset;
#[cfg(feature = "GcArmyExpedition")]
pub mod GcArmyExpedition;
#[cfg(feature = "GcArmyExpeditionMemberBonus")]
pub mod GcArmyExpeditionMemberBonus;
#[cfg(feature = "GcArmyExpeditionTrait")]
pub mod GcArmyExpeditionTrait;
#[cfg(feature = "GcArmyExpeditionTraitCond")]
pub mod GcArmyExpeditionTraitCond;
#[cfg(feature = "GcArmyExpeditionType")]
pub mod GcArmyExpeditionType;
#[cfg(feature = "GcArmyMember")]
pub mod GcArmyMember;
#[cfg(feature = "GcArmyMemberGrow")]
pub mod GcArmyMemberGrow;
#[cfg(feature = "GcArmyMemberGrowExp")]
pub mod GcArmyMemberGrowExp;
#[cfg(feature = "GcArmyProgress")]
pub mod GcArmyProgress;
#[cfg(feature = "GcArmyTraining")]
pub mod GcArmyTraining;
#[cfg(feature = "GeneralAction")]
pub mod GeneralAction;
#[cfg(feature = "GilShop")]
pub mod GilShop;
#[cfg(feature = "GilShopInfo")]
pub mod GilShopInfo;
#[cfg(feature = "GilShopItem")]
pub mod GilShopItem;
#[cfg(feature = "GimmickAccessor")]
pub mod GimmickAccessor;
#[cfg(feature = "GimmickBill")]
pub mod GimmickBill;
#[cfg(feature = "GimmickJump")]
pub mod GimmickJump;
#[cfg(feature = "GimmickRect")]
pub mod GimmickRect;
#[cfg(feature = "GimmickTalk")]
pub mod GimmickTalk;
#[cfg(feature = "GimmickYesNo")]
pub mod GimmickYesNo;
#[cfg(feature = "Glasses")]
pub mod Glasses;
#[cfg(feature = "GlassesStyle")]
pub mod GlassesStyle;
#[cfg(feature = "GoldSaucerArcadeMachine")]
pub mod GoldSaucerArcadeMachine;
#[cfg(feature = "GoldSaucerContent")]
pub mod GoldSaucerContent;
#[cfg(feature = "GoldSaucerTalk")]
pub mod GoldSaucerTalk;
#[cfg(feature = "GoldSaucerTextData")]
pub mod GoldSaucerTextData;
#[cfg(feature = "GrandCompany")]
pub mod GrandCompany;
#[cfg(feature = "GrandCompanyRank")]
pub mod GrandCompanyRank;
#[cfg(feature = "GroupPoseCharaStatus")]
pub mod GroupPoseCharaStatus;
#[cfg(feature = "GroupPoseCharacterShowPreset")]
pub mod GroupPoseCharacterShowPreset;
#[cfg(feature = "GroupPoseFrame")]
pub mod GroupPoseFrame;
#[cfg(feature = "GroupPoseStamp")]
pub mod GroupPoseStamp;
#[cfg(feature = "GroupPoseStampCategory")]
pub mod GroupPoseStampCategory;
#[cfg(feature = "GroupPoseStampFontColor")]
pub mod GroupPoseStampFontColor;
#[cfg(feature = "GuardianDeity")]
pub mod GuardianDeity;
#[cfg(feature = "Guide")]
pub mod Guide;
#[cfg(feature = "GuidePage")]
pub mod GuidePage;
#[cfg(feature = "GuidePageString")]
pub mod GuidePageString;
#[cfg(feature = "GuideTitle")]
pub mod GuideTitle;
#[cfg(feature = "GuildOrder")]
pub mod GuildOrder;
#[cfg(feature = "GuildOrderGuide")]
pub mod GuildOrderGuide;
#[cfg(feature = "GuildOrderOfficer")]
pub mod GuildOrderOfficer;
#[cfg(feature = "GuildleveAssignment")]
pub mod GuildleveAssignment;
#[cfg(feature = "GuildleveAssignmentCategory")]
pub mod GuildleveAssignmentCategory;
#[cfg(feature = "GuildleveAssignmentTalk")]
pub mod GuildleveAssignmentTalk;
#[cfg(feature = "HWDAnnounce")]
pub mod HWDAnnounce;
#[cfg(feature = "HWDCrafterSupply")]
pub mod HWDCrafterSupply;
#[cfg(feature = "HWDCrafterSupplyReward")]
pub mod HWDCrafterSupplyReward;
#[cfg(feature = "HWDCrafterSupplyTerm")]
pub mod HWDCrafterSupplyTerm;
#[cfg(feature = "HWDDevLayerControl")]
pub mod HWDDevLayerControl;
#[cfg(feature = "HWDDevLevelUI")]
pub mod HWDDevLevelUI;
#[cfg(feature = "HWDDevLevelWebText")]
pub mod HWDDevLevelWebText;
#[cfg(feature = "HWDDevLively")]
pub mod HWDDevLively;
#[cfg(feature = "HWDDevProgress")]
pub mod HWDDevProgress;
#[cfg(feature = "HWDGathereInspectTerm")]
pub mod HWDGathereInspectTerm;
#[cfg(feature = "HWDGathererInspection")]
pub mod HWDGathererInspection;
#[cfg(feature = "HWDGathererInspectionReward")]
pub mod HWDGathererInspectionReward;
#[cfg(feature = "HWDInfoBoardArticle")]
pub mod HWDInfoBoardArticle;
#[cfg(feature = "HWDInfoBoardArticleTransient")]
pub mod HWDInfoBoardArticleTransient;
#[cfg(feature = "HWDInfoBoardArticleType")]
pub mod HWDInfoBoardArticleType;
#[cfg(feature = "HWDInfoBoardBackNumber")]
pub mod HWDInfoBoardBackNumber;
#[cfg(feature = "HWDLevelChangeDeception")]
pub mod HWDLevelChangeDeception;
#[cfg(feature = "HWDSharedGroup")]
pub mod HWDSharedGroup;
#[cfg(feature = "HWDSharedGroupControlParam")]
pub mod HWDSharedGroupControlParam;
#[cfg(feature = "HairMakeType")]
pub mod HairMakeType;
#[cfg(feature = "HouseRetainerPose")]
pub mod HouseRetainerPose;
#[cfg(feature = "HousingAethernet")]
pub mod HousingAethernet;
#[cfg(feature = "HousingAppeal")]
pub mod HousingAppeal;
#[cfg(feature = "HousingEmploymentNpcList")]
pub mod HousingEmploymentNpcList;
#[cfg(feature = "HousingEmploymentNpcRace")]
pub mod HousingEmploymentNpcRace;
#[cfg(feature = "HousingExterior")]
pub mod HousingExterior;
#[cfg(feature = "HousingFurniture")]
pub mod HousingFurniture;
#[cfg(feature = "HousingIndoorTerritory")]
pub mod HousingIndoorTerritory;
#[cfg(feature = "HousingInterior")]
pub mod HousingInterior;
#[cfg(feature = "HousingLandSet")]
pub mod HousingLandSet;
#[cfg(feature = "HousingMapMarkerInfo")]
pub mod HousingMapMarkerInfo;
#[cfg(feature = "HousingMateAuthority")]
pub mod HousingMateAuthority;
#[cfg(feature = "HousingMerchantPose")]
pub mod HousingMerchantPose;
#[cfg(feature = "HousingPileLimit")]
pub mod HousingPileLimit;
#[cfg(feature = "HousingPlacement")]
pub mod HousingPlacement;
#[cfg(feature = "HousingPreset")]
pub mod HousingPreset;
#[cfg(feature = "HousingRenovation")]
pub mod HousingRenovation;
#[cfg(feature = "HousingTrainingDoll")]
pub mod HousingTrainingDoll;
#[cfg(feature = "HousingUnitedExterior")]
pub mod HousingUnitedExterior;
#[cfg(feature = "HousingUnplacement")]
pub mod HousingUnplacement;
#[cfg(feature = "HousingYardObject")]
pub mod HousingYardObject;
#[cfg(feature = "HowTo")]
pub mod HowTo;
#[cfg(feature = "HowToCategory")]
pub mod HowToCategory;
#[cfg(feature = "HowToPage")]
pub mod HowToPage;
#[cfg(feature = "Hud")]
pub mod Hud;
#[cfg(feature = "HudTransient")]
pub mod HudTransient;
#[cfg(feature = "HugeCraftworksNpc")]
pub mod HugeCraftworksNpc;
#[cfg(feature = "HugeCraftworksRank")]
pub mod HugeCraftworksRank;
#[cfg(feature = "IKDContentBonus")]
pub mod IKDContentBonus;
#[cfg(feature = "IKDFishParam")]
pub mod IKDFishParam;
#[cfg(feature = "IKDPlayerMissionCondition")]
pub mod IKDPlayerMissionCondition;
#[cfg(feature = "IKDRoute")]
pub mod IKDRoute;
#[cfg(feature = "IKDRouteTable")]
pub mod IKDRouteTable;
#[cfg(feature = "IKDSpot")]
pub mod IKDSpot;
#[cfg(feature = "IKDTimeDefine")]
pub mod IKDTimeDefine;
#[cfg(feature = "IconLanguage")]
pub mod IconLanguage;
#[cfg(feature = "InclusionShop")]
pub mod InclusionShop;
#[cfg(feature = "InclusionShopCategory")]
pub mod InclusionShopCategory;
#[cfg(feature = "InclusionShopSeries")]
pub mod InclusionShopSeries;
#[cfg(feature = "InclusionShopWelcom")]
pub mod InclusionShopWelcom;
#[cfg(feature = "InclusionShopWelcomText")]
pub mod InclusionShopWelcomText;
#[cfg(feature = "IndividualWeather")]
pub mod IndividualWeather;
#[cfg(feature = "InstanceContent")]
pub mod InstanceContent;
#[cfg(feature = "InstanceContentBuff")]
pub mod InstanceContentBuff;
#[cfg(feature = "InstanceContentGuide")]
pub mod InstanceContentGuide;
#[cfg(feature = "InstanceContentQICData")]
pub mod InstanceContentQICData;
#[cfg(feature = "InstanceContentRewardItem")]
pub mod InstanceContentRewardItem;
#[cfg(feature = "InstanceContentTextData")]
pub mod InstanceContentTextData;
#[cfg(feature = "InstanceContentType")]
pub mod InstanceContentType;
#[cfg(feature = "Item")]
pub mod Item;
#[cfg(feature = "ItemAction")]
pub mod ItemAction;
#[cfg(feature = "ItemActionTelepo")]
pub mod ItemActionTelepo;
#[cfg(feature = "ItemBarterCheck")]
pub mod ItemBarterCheck;
#[cfg(feature = "ItemBarterWarning")]
pub mod ItemBarterWarning;
#[cfg(feature = "ItemFood")]
pub mod ItemFood;
#[cfg(feature = "ItemLevel")]
pub mod ItemLevel;
#[cfg(feature = "ItemOnceHqMasterpiece")]
pub mod ItemOnceHqMasterpiece;
#[cfg(feature = "ItemRepairPrice")]
pub mod ItemRepairPrice;
#[cfg(feature = "ItemRepairResource")]
pub mod ItemRepairResource;
#[cfg(feature = "ItemRetainerLevelUp")]
pub mod ItemRetainerLevelUp;
#[cfg(feature = "ItemSearchCategory")]
pub mod ItemSearchCategory;
#[cfg(feature = "ItemSeries")]
pub mod ItemSeries;
#[cfg(feature = "ItemSortCategory")]
pub mod ItemSortCategory;
#[cfg(feature = "ItemSpecialBonus")]
pub mod ItemSpecialBonus;
#[cfg(feature = "ItemStainCondition")]
pub mod ItemStainCondition;
#[cfg(feature = "ItemUICategory")]
pub mod ItemUICategory;
#[cfg(feature = "JigsawScore")]
pub mod JigsawScore;
#[cfg(feature = "JigsawTimeBonus")]
pub mod JigsawTimeBonus;
#[cfg(feature = "Jingle")]
pub mod Jingle;
#[cfg(feature = "JobHudManual")]
pub mod JobHudManual;
#[cfg(feature = "JobHudManualPriority")]
pub mod JobHudManualPriority;
#[cfg(feature = "JournalCategory")]
pub mod JournalCategory;
#[cfg(feature = "JournalGenre")]
pub mod JournalGenre;
#[cfg(feature = "JournalSection")]
pub mod JournalSection;
#[cfg(feature = "KineDriverOffGroup")]
pub mod KineDriverOffGroup;
#[cfg(feature = "Knockback")]
pub mod Knockback;
#[cfg(feature = "LFGExtensionContent")]
pub mod LFGExtensionContent;
#[cfg(feature = "LegacyQuest")]
pub mod LegacyQuest;
#[cfg(feature = "Leve")]
pub mod Leve;
#[cfg(feature = "LeveAssignmentType")]
pub mod LeveAssignmentType;
#[cfg(feature = "LeveClient")]
pub mod LeveClient;
#[cfg(feature = "LeveRewardItem")]
pub mod LeveRewardItem;
#[cfg(feature = "LeveRewardItemGroup")]
pub mod LeveRewardItemGroup;
#[cfg(feature = "LeveString")]
pub mod LeveString;
#[cfg(feature = "LeveSystemDefine")]
pub mod LeveSystemDefine;
#[cfg(feature = "LeveVfx")]
pub mod LeveVfx;
#[cfg(feature = "Level")]
pub mod Level;
#[cfg(feature = "LinkRace")]
pub mod LinkRace;
#[cfg(feature = "LivelyActorGroup")]
pub mod LivelyActorGroup;
#[cfg(feature = "LoadingImage")]
pub mod LoadingImage;
#[cfg(feature = "LoadingTips")]
pub mod LoadingTips;
#[cfg(feature = "LoadingTipsSub")]
pub mod LoadingTipsSub;
#[cfg(feature = "Lobby")]
pub mod Lobby;
#[cfg(feature = "Lockon")]
pub mod Lockon;
#[cfg(feature = "LogFilter")]
pub mod LogFilter;
#[cfg(feature = "LogKind")]
pub mod LogKind;
#[cfg(feature = "LogMessage")]
pub mod LogMessage;
#[cfg(feature = "LootModeType")]
pub mod LootModeType;
#[cfg(feature = "LotteryExchangeShop")]
pub mod LotteryExchangeShop;
#[cfg(feature = "MJIAnimals")]
pub mod MJIAnimals;
#[cfg(feature = "MJIBuilding")]
pub mod MJIBuilding;
#[cfg(feature = "MJIBuildingPlace")]
pub mod MJIBuildingPlace;
#[cfg(feature = "MJICraftworksObject")]
pub mod MJICraftworksObject;
#[cfg(feature = "MJICraftworksObjectTheme")]
pub mod MJICraftworksObjectTheme;
#[cfg(feature = "MJICraftworksPopularity")]
pub mod MJICraftworksPopularity;
#[cfg(feature = "MJICraftworksPopularityType")]
pub mod MJICraftworksPopularityType;
#[cfg(feature = "MJICraftworksRankRatio")]
pub mod MJICraftworksRankRatio;
#[cfg(feature = "MJICraftworksSupplyDefine")]
pub mod MJICraftworksSupplyDefine;
#[cfg(feature = "MJICraftworksTension")]
pub mod MJICraftworksTension;
#[cfg(feature = "MJICropSeed")]
pub mod MJICropSeed;
#[cfg(feature = "MJIDisposalShopItem")]
pub mod MJIDisposalShopItem;
#[cfg(feature = "MJIDisposalShopUICategory")]
pub mod MJIDisposalShopUICategory;
#[cfg(feature = "MJIFarmPastureRank")]
pub mod MJIFarmPastureRank;
#[cfg(feature = "MJIFunction")]
pub mod MJIFunction;
#[cfg(feature = "MJIGardenscaping")]
pub mod MJIGardenscaping;
#[cfg(feature = "MJIGathering")]
pub mod MJIGathering;
#[cfg(feature = "MJIGatheringItem")]
pub mod MJIGatheringItem;
#[cfg(feature = "MJIGatheringObject")]
pub mod MJIGatheringObject;
#[cfg(feature = "MJIGatheringTool")]
pub mod MJIGatheringTool;
#[cfg(feature = "MJIHudMode")]
pub mod MJIHudMode;
#[cfg(feature = "MJIItemCategory")]
pub mod MJIItemCategory;
#[cfg(feature = "MJIItemPouch")]
pub mod MJIItemPouch;
#[cfg(feature = "MJIKeyItem")]
pub mod MJIKeyItem;
#[cfg(feature = "MJILandmark")]
pub mod MJILandmark;
#[cfg(feature = "MJILandmarkPlace")]
pub mod MJILandmarkPlace;
#[cfg(feature = "MJILivelyActor")]
pub mod MJILivelyActor;
#[cfg(feature = "MJIMinionPopAreas")]
pub mod MJIMinionPopAreas;
#[cfg(feature = "MJIName")]
pub mod MJIName;
#[cfg(feature = "MJINekomimiRequest")]
pub mod MJINekomimiRequest;
#[cfg(feature = "MJIProgress")]
pub mod MJIProgress;
#[cfg(feature = "MJIRank")]
pub mod MJIRank;
#[cfg(feature = "MJIRecipe")]
pub mod MJIRecipe;
#[cfg(feature = "MJIRecipeMaterial")]
pub mod MJIRecipeMaterial;
#[cfg(feature = "MJIStockyardManagementArea")]
pub mod MJIStockyardManagementArea;
#[cfg(feature = "MJIStockyardManagementTable")]
pub mod MJIStockyardManagementTable;
#[cfg(feature = "MJIText")]
pub mod MJIText;
#[cfg(feature = "MJIVillageAppearanceSG")]
pub mod MJIVillageAppearanceSG;
#[cfg(feature = "MJIVillageAppearanceUI")]
pub mod MJIVillageAppearanceUI;
#[cfg(feature = "MJIVillageDevelopment")]
pub mod MJIVillageDevelopment;
#[cfg(feature = "MKDBNpcData")]
pub mod MKDBNpcData;
#[cfg(feature = "MKDChain")]
pub mod MKDChain;
#[cfg(feature = "MKDData")]
pub mod MKDData;
#[cfg(feature = "MKDGrowData")]
pub mod MKDGrowData;
#[cfg(feature = "MKDGrowDataSJob")]
pub mod MKDGrowDataSJob;
#[cfg(feature = "MKDLore")]
pub mod MKDLore;
#[cfg(feature = "MKDSupportJob")]
pub mod MKDSupportJob;
#[cfg(feature = "MKDTrait")]
pub mod MKDTrait;
#[cfg(feature = "MYCTemporaryItem")]
pub mod MYCTemporaryItem;
#[cfg(feature = "MYCTemporaryItemUICategory")]
pub mod MYCTemporaryItemUICategory;
#[cfg(feature = "MYCWarResultNotebook")]
pub mod MYCWarResultNotebook;
#[cfg(feature = "MacroIcon")]
pub mod MacroIcon;
#[cfg(feature = "MacroIconRedirectOld")]
pub mod MacroIconRedirectOld;
#[cfg(feature = "MainCommand")]
pub mod MainCommand;
#[cfg(feature = "MainCommandCategory")]
pub mod MainCommandCategory;
#[cfg(feature = "MandervilleWeaponEnhance")]
pub mod MandervilleWeaponEnhance;
#[cfg(feature = "Maneuvers")]
pub mod Maneuvers;
#[cfg(feature = "ManeuversArmor")]
pub mod ManeuversArmor;
#[cfg(feature = "Map")]
pub mod Map;
#[cfg(feature = "MapCondition")]
pub mod MapCondition;
#[cfg(feature = "MapExclusive")]
pub mod MapExclusive;
#[cfg(feature = "MapMarker")]
pub mod MapMarker;
#[cfg(feature = "MapMarkerRegion")]
pub mod MapMarkerRegion;
#[cfg(feature = "MapReplace")]
pub mod MapReplace;
#[cfg(feature = "MapSymbol")]
pub mod MapSymbol;
#[cfg(feature = "MapTransientPvPMap")]
pub mod MapTransientPvPMap;
#[cfg(feature = "MapType")]
pub mod MapType;
#[cfg(feature = "Marker")]
pub mod Marker;
#[cfg(feature = "MassivePcContent")]
pub mod MassivePcContent;
#[cfg(feature = "MassivePcContentBattleTalk")]
pub mod MassivePcContentBattleTalk;
#[cfg(feature = "MassivePcContentTextData")]
pub mod MassivePcContentTextData;
#[cfg(feature = "MassivePcContentTodo")]
pub mod MassivePcContentTodo;
#[cfg(feature = "MateAuthorityCategory")]
pub mod MateAuthorityCategory;
#[cfg(feature = "Materia")]
pub mod Materia;
#[cfg(feature = "MateriaGrade")]
pub mod MateriaGrade;
#[cfg(feature = "MateriaJoinRate")]
pub mod MateriaJoinRate;
#[cfg(feature = "MateriaJoinRateGatherCraft")]
pub mod MateriaJoinRateGatherCraft;
#[cfg(feature = "MateriaParam")]
pub mod MateriaParam;
#[cfg(feature = "McGuffin")]
pub mod McGuffin;
#[cfg(feature = "McGuffinUIData")]
pub mod McGuffinUIData;
#[cfg(feature = "MiniGameRA")]
pub mod MiniGameRA;
#[cfg(feature = "MiniGameRANotes")]
pub mod MiniGameRANotes;
#[cfg(feature = "MiniGameTurnBreakAction")]
pub mod MiniGameTurnBreakAction;
#[cfg(feature = "MiniGameTurnBreakConst")]
pub mod MiniGameTurnBreakConst;
#[cfg(feature = "MiniGameTurnBreakEnemy")]
pub mod MiniGameTurnBreakEnemy;
#[cfg(feature = "MiniGameTurnBreakPop")]
pub mod MiniGameTurnBreakPop;
#[cfg(feature = "MiniGameTurnBreakPopOffset")]
pub mod MiniGameTurnBreakPopOffset;
#[cfg(feature = "MiniGameTurnBreakStage")]
pub mod MiniGameTurnBreakStage;
#[cfg(feature = "MiniGameTurnBreakStatus")]
pub mod MiniGameTurnBreakStatus;
#[cfg(feature = "MinionRace")]
pub mod MinionRace;
#[cfg(feature = "MinionRules")]
pub mod MinionRules;
#[cfg(feature = "MinionSkillType")]
pub mod MinionSkillType;
#[cfg(feature = "MinionStage")]
pub mod MinionStage;
#[cfg(feature = "MirageStoreSetItem")]
pub mod MirageStoreSetItem;
#[cfg(feature = "MirageStoreSetItemLookup")]
pub mod MirageStoreSetItemLookup;
#[cfg(feature = "MobHuntOrder")]
pub mod MobHuntOrder;
#[cfg(feature = "MobHuntOrderType")]
pub mod MobHuntOrderType;
#[cfg(feature = "MobHuntReward")]
pub mod MobHuntReward;
#[cfg(feature = "MobHuntRewardCap")]
pub mod MobHuntRewardCap;
#[cfg(feature = "MobHuntTarget")]
pub mod MobHuntTarget;
#[cfg(feature = "ModelAttribute")]
pub mod ModelAttribute;
#[cfg(feature = "ModelChara")]
pub mod ModelChara;
#[cfg(feature = "ModelScale")]
pub mod ModelScale;
#[cfg(feature = "ModelSkeleton")]
pub mod ModelSkeleton;
#[cfg(feature = "ModelState")]
pub mod ModelState;
#[cfg(feature = "MonsterNote")]
pub mod MonsterNote;
#[cfg(feature = "MonsterNoteTarget")]
pub mod MonsterNoteTarget;
#[cfg(feature = "MotionTimeline")]
pub mod MotionTimeline;
#[cfg(feature = "MotionTimelineAdvanceBlend")]
pub mod MotionTimelineAdvanceBlend;
#[cfg(feature = "MotionTimelineBlendTable")]
pub mod MotionTimelineBlendTable;
#[cfg(feature = "Mount")]
pub mod Mount;
#[cfg(feature = "MountAction")]
pub mod MountAction;
#[cfg(feature = "MountCustomize")]
pub mod MountCustomize;
#[cfg(feature = "MountFlyingCondition")]
pub mod MountFlyingCondition;
#[cfg(feature = "MountSpeed")]
pub mod MountSpeed;
#[cfg(feature = "MountTransient")]
pub mod MountTransient;
#[cfg(feature = "MoveControl")]
pub mod MoveControl;
#[cfg(feature = "MoveTimeline")]
pub mod MoveTimeline;
#[cfg(feature = "MoveVfx")]
pub mod MoveVfx;
#[cfg(feature = "MovieStaffList")]
pub mod MovieStaffList;
#[cfg(feature = "MovieSubtitle")]
pub mod MovieSubtitle;
#[cfg(feature = "MovieSubtitle500")]
pub mod MovieSubtitle500;
#[cfg(feature = "MovieSubtitleVoyage")]
pub mod MovieSubtitleVoyage;
#[cfg(feature = "MultipleHelp")]
pub mod MultipleHelp;
#[cfg(feature = "MultipleHelpPage")]
pub mod MultipleHelpPage;
#[cfg(feature = "MultipleHelpString")]
pub mod MultipleHelpString;
#[cfg(feature = "NotebookDivision")]
pub mod NotebookDivision;
#[cfg(feature = "NotebookDivisionCategory")]
pub mod NotebookDivisionCategory;
#[cfg(feature = "NotebookList")]
pub mod NotebookList;
#[cfg(feature = "NotoriousMonster")]
pub mod NotoriousMonster;
#[cfg(feature = "NotoriousMonsterTerritory")]
pub mod NotoriousMonsterTerritory;
#[cfg(feature = "NpcEquip")]
pub mod NpcEquip;
#[cfg(feature = "NpcYell")]
pub mod NpcYell;
#[cfg(feature = "Omen")]
pub mod Omen;
#[cfg(feature = "Omikuji")]
pub mod Omikuji;
#[cfg(feature = "OmikujiGuidance")]
pub mod OmikujiGuidance;
#[cfg(feature = "OnlineStatus")]
pub mod OnlineStatus;
#[cfg(feature = "OpenContent")]
pub mod OpenContent;
#[cfg(feature = "OpenContentCandidateName")]
pub mod OpenContentCandidateName;
#[cfg(feature = "OpenLuaUI")]
pub mod OpenLuaUI;
#[cfg(feature = "Opening")]
pub mod Opening;
#[cfg(feature = "OpeningSystemDefine")]
pub mod OpeningSystemDefine;
#[cfg(feature = "Orchestrion")]
pub mod Orchestrion;
#[cfg(feature = "OrchestrionCategory")]
pub mod OrchestrionCategory;
#[cfg(feature = "OrchestrionPath")]
pub mod OrchestrionPath;
#[cfg(feature = "OrchestrionUiparam")]
pub mod OrchestrionUiparam;
#[cfg(feature = "Ornament")]
pub mod Ornament;
#[cfg(feature = "OrnamentAction")]
pub mod OrnamentAction;
#[cfg(feature = "OrnamentCustomize")]
pub mod OrnamentCustomize;
#[cfg(feature = "OrnamentCustomizeGroup")]
pub mod OrnamentCustomizeGroup;
#[cfg(feature = "OrnamentTransient")]
pub mod OrnamentTransient;
#[cfg(feature = "ParamGrow")]
pub mod ParamGrow;
#[cfg(feature = "PartyContent")]
pub mod PartyContent;
#[cfg(feature = "PartyContentCutscene")]
pub mod PartyContentCutscene;
#[cfg(feature = "PartyContentTextData")]
pub mod PartyContentTextData;
#[cfg(feature = "PartyContentTransient")]
pub mod PartyContentTransient;
#[cfg(feature = "PatchMark")]
pub mod PatchMark;
#[cfg(feature = "Perform")]
pub mod Perform;
#[cfg(feature = "PerformGroup")]
pub mod PerformGroup;
#[cfg(feature = "PerformGuideScore")]
pub mod PerformGuideScore;
#[cfg(feature = "PerformTransient")]
pub mod PerformTransient;
#[cfg(feature = "Permission")]
pub mod Permission;
#[cfg(feature = "Pet")]
pub mod Pet;
#[cfg(feature = "PetAction")]
pub mod PetAction;
#[cfg(feature = "PetMirage")]
pub mod PetMirage;
#[cfg(feature = "PhysicsGroup")]
pub mod PhysicsGroup;
#[cfg(feature = "PhysicsOffGroup")]
pub mod PhysicsOffGroup;
#[cfg(feature = "PhysicsParameter")]
pub mod PhysicsParameter;
#[cfg(feature = "PhysicsWind")]
pub mod PhysicsWind;
#[cfg(feature = "Picture")]
pub mod Picture;
#[cfg(feature = "PlaceName")]
pub mod PlaceName;
#[cfg(feature = "PlaceNameReplace")]
pub mod PlaceNameReplace;
#[cfg(feature = "PlantPotFlowerSeed")]
pub mod PlantPotFlowerSeed;
#[cfg(feature = "PlayerSearchLocation")]
pub mod PlayerSearchLocation;
#[cfg(feature = "PlayerSearchSubLocation")]
pub mod PlayerSearchSubLocation;
#[cfg(feature = "PointMenu")]
pub mod PointMenu;
#[cfg(feature = "PointMenuChoice")]
pub mod PointMenuChoice;
#[cfg(feature = "PointMenuString")]
pub mod PointMenuString;
#[cfg(feature = "PreHandler")]
pub mod PreHandler;
#[cfg(feature = "PreHandlerMovement")]
pub mod PreHandlerMovement;
#[cfg(feature = "PresetCamera")]
pub mod PresetCamera;
#[cfg(feature = "PresetCameraAdjust")]
pub mod PresetCameraAdjust;
#[cfg(feature = "PreviewableItems")]
pub mod PreviewableItems;
#[cfg(feature = "PublicContent")]
pub mod PublicContent;
#[cfg(feature = "PublicContentCutscene")]
pub mod PublicContentCutscene;
#[cfg(feature = "PublicContentTextData")]
pub mod PublicContentTextData;
#[cfg(feature = "PublicContentType")]
pub mod PublicContentType;
#[cfg(feature = "PvPAction")]
pub mod PvPAction;
#[cfg(feature = "PvPActionSort")]
pub mod PvPActionSort;
#[cfg(feature = "PvPBaseParamValue")]
pub mod PvPBaseParamValue;
#[cfg(feature = "PvPInitialSelectActionTrait")]
pub mod PvPInitialSelectActionTrait;
#[cfg(feature = "PvPRank")]
pub mod PvPRank;
#[cfg(feature = "PvPRankTransient")]
pub mod PvPRankTransient;
#[cfg(feature = "PvPSelectAction")]
pub mod PvPSelectAction;
#[cfg(feature = "PvPSelectTrait")]
pub mod PvPSelectTrait;
#[cfg(feature = "PvPSelectTraitTransient")]
pub mod PvPSelectTraitTransient;
#[cfg(feature = "PvPSeries")]
pub mod PvPSeries;
#[cfg(feature = "PvPSeriesLevel")]
pub mod PvPSeriesLevel;
#[cfg(feature = "PvPTrait")]
pub mod PvPTrait;
#[cfg(feature = "QTE")]
pub mod QTE;
#[cfg(feature = "Quest")]
pub mod Quest;
#[cfg(feature = "QuestAcceptAdditionCondition")]
pub mod QuestAcceptAdditionCondition;
#[cfg(feature = "QuestAdditionalToolIcon")]
pub mod QuestAdditionalToolIcon;
#[cfg(feature = "QuestAroundPlayerHide")]
pub mod QuestAroundPlayerHide;
#[cfg(feature = "QuestAroundPlayerHideExt")]
pub mod QuestAroundPlayerHideExt;
#[cfg(feature = "QuestBattle")]
pub mod QuestBattle;
#[cfg(feature = "QuestBattleResident")]
pub mod QuestBattleResident;
#[cfg(feature = "QuestBattleSystemDefine")]
pub mod QuestBattleSystemDefine;
#[cfg(feature = "QuestChapter")]
pub mod QuestChapter;
#[cfg(feature = "QuestClassJobReward")]
pub mod QuestClassJobReward;
#[cfg(feature = "QuestClassJobSupply")]
pub mod QuestClassJobSupply;
#[cfg(feature = "QuestCustomTodo")]
pub mod QuestCustomTodo;
#[cfg(feature = "QuestDefineClient")]
pub mod QuestDefineClient;
#[cfg(feature = "QuestDerivedClass")]
pub mod QuestDerivedClass;
#[cfg(feature = "QuestEffect")]
pub mod QuestEffect;
#[cfg(feature = "QuestEffectDefine")]
pub mod QuestEffectDefine;
#[cfg(feature = "QuestEffectType")]
pub mod QuestEffectType;
#[cfg(feature = "QuestEquipModel")]
pub mod QuestEquipModel;
#[cfg(feature = "QuestEventAreaEntranceInfo")]
pub mod QuestEventAreaEntranceInfo;
#[cfg(feature = "QuestHideReward")]
pub mod QuestHideReward;
#[cfg(feature = "QuestLinkMarker")]
pub mod QuestLinkMarker;
#[cfg(feature = "QuestLinkMarkerIcon")]
pub mod QuestLinkMarkerIcon;
#[cfg(feature = "QuestLinkMarkerSet")]
pub mod QuestLinkMarkerSet;
#[cfg(feature = "QuestRecomplete")]
pub mod QuestRecomplete;
#[cfg(feature = "QuestRedo")]
pub mod QuestRedo;
#[cfg(feature = "QuestRedoChapter")]
pub mod QuestRedoChapter;
#[cfg(feature = "QuestRedoChapterUI")]
pub mod QuestRedoChapterUI;
#[cfg(feature = "QuestRedoChapterUICategory")]
pub mod QuestRedoChapterUICategory;
#[cfg(feature = "QuestRedoChapterUITab")]
pub mod QuestRedoChapterUITab;
#[cfg(feature = "QuestRedoIncompChapter")]
pub mod QuestRedoIncompChapter;
#[cfg(feature = "QuestRedoValidCustomTalk")]
pub mod QuestRedoValidCustomTalk;
#[cfg(feature = "QuestRepeatFlag")]
pub mod QuestRepeatFlag;
#[cfg(feature = "QuestRewardOther")]
pub mod QuestRewardOther;
#[cfg(feature = "QuestSceneAbortCondition")]
pub mod QuestSceneAbortCondition;
#[cfg(feature = "QuestSceneAbortConditionFlag")]
pub mod QuestSceneAbortConditionFlag;
#[cfg(feature = "QuestSceneAbortConditionType")]
pub mod QuestSceneAbortConditionType;
#[cfg(feature = "QuestSelectTitle")]
pub mod QuestSelectTitle;
#[cfg(feature = "QuestSetDefine")]
pub mod QuestSetDefine;
#[cfg(feature = "QuestStatusParam")]
pub mod QuestStatusParam;
#[cfg(feature = "QuestSubCommand")]
pub mod QuestSubCommand;
#[cfg(feature = "QuestSystemDefine")]
pub mod QuestSystemDefine;
#[cfg(feature = "QuickChat")]
pub mod QuickChat;
#[cfg(feature = "QuickChatTransient")]
pub mod QuickChatTransient;
#[cfg(feature = "RPParameter")]
pub mod RPParameter;
#[cfg(feature = "Race")]
pub mod Race;
#[cfg(feature = "RacingChocoboGrade")]
pub mod RacingChocoboGrade;
#[cfg(feature = "RacingChocoboItem")]
pub mod RacingChocoboItem;
#[cfg(feature = "RacingChocoboName")]
pub mod RacingChocoboName;
#[cfg(feature = "RacingChocoboNameCategory")]
pub mod RacingChocoboNameCategory;
#[cfg(feature = "RacingChocoboNameInfo")]
pub mod RacingChocoboNameInfo;
#[cfg(feature = "RacingChocoboParam")]
pub mod RacingChocoboParam;
#[cfg(feature = "RaidFinderParam")]
pub mod RaidFinderParam;
#[cfg(feature = "ReactionEventObject")]
pub mod ReactionEventObject;
#[cfg(feature = "ReactionEventObjectInfo")]
pub mod ReactionEventObjectInfo;
#[cfg(feature = "RecastNavimesh")]
pub mod RecastNavimesh;
#[cfg(feature = "Recipe")]
pub mod Recipe;
#[cfg(feature = "RecipeLevelTable")]
pub mod RecipeLevelTable;
#[cfg(feature = "RecipeLookup")]
pub mod RecipeLookup;
#[cfg(feature = "RecipeNotebookList")]
pub mod RecipeNotebookList;
#[cfg(feature = "RecipeSubCategory")]
pub mod RecipeSubCategory;
#[cfg(feature = "RecommendContents")]
pub mod RecommendContents;
#[cfg(feature = "Relic")]
pub mod Relic;
#[cfg(feature = "Relic3")]
pub mod Relic3;
#[cfg(feature = "Relic3Materia")]
pub mod Relic3Materia;
#[cfg(feature = "Relic3Rate")]
pub mod Relic3Rate;
#[cfg(feature = "Relic3RatePattern")]
pub mod Relic3RatePattern;
#[cfg(feature = "Relic6Magicite")]
pub mod Relic6Magicite;
#[cfg(feature = "RelicItem")]
pub mod RelicItem;
#[cfg(feature = "RelicMateria")]
pub mod RelicMateria;
#[cfg(feature = "RelicNote")]
pub mod RelicNote;
#[cfg(feature = "RelicNoteCategory")]
pub mod RelicNoteCategory;
#[cfg(feature = "ReplaceAction")]
pub mod ReplaceAction;
#[cfg(feature = "Resident")]
pub mod Resident;
#[cfg(feature = "ResidentMotionType")]
pub mod ResidentMotionType;
#[cfg(feature = "ResistanceWeaponAdjust")]
pub mod ResistanceWeaponAdjust;
#[cfg(feature = "RetainerFortuneRewardRange")]
pub mod RetainerFortuneRewardRange;
#[cfg(feature = "RetainerTask")]
pub mod RetainerTask;
#[cfg(feature = "RetainerTaskLvRange")]
pub mod RetainerTaskLvRange;
#[cfg(feature = "RetainerTaskNormal")]
pub mod RetainerTaskNormal;
#[cfg(feature = "RetainerTaskParameter")]
pub mod RetainerTaskParameter;
#[cfg(feature = "RetainerTaskParameterLvDiff")]
pub mod RetainerTaskParameterLvDiff;
#[cfg(feature = "RetainerTaskRandom")]
pub mod RetainerTaskRandom;
#[cfg(feature = "RideShooting")]
pub mod RideShooting;
#[cfg(feature = "RideShootingScheduler")]
pub mod RideShootingScheduler;
#[cfg(feature = "RideShootingTarget")]
pub mod RideShootingTarget;
#[cfg(feature = "RideShootingTargetScheduler")]
pub mod RideShootingTargetScheduler;
#[cfg(feature = "RideShootingTargetType")]
pub mod RideShootingTargetType;
#[cfg(feature = "RideShootingTextData")]
pub mod RideShootingTextData;
#[cfg(feature = "Role")]
pub mod Role;
#[cfg(feature = "SE")]
pub mod SE;
#[cfg(feature = "SEBattle")]
pub mod SEBattle;
#[cfg(feature = "SatisfactionArbitration")]
pub mod SatisfactionArbitration;
#[cfg(feature = "SatisfactionBonusGuarantee")]
pub mod SatisfactionBonusGuarantee;
#[cfg(feature = "SatisfactionNpc")]
pub mod SatisfactionNpc;
#[cfg(feature = "SatisfactionSupply")]
pub mod SatisfactionSupply;
#[cfg(feature = "SatisfactionSupplyReward")]
pub mod SatisfactionSupplyReward;
#[cfg(feature = "SatisfactionSupplyRewardExp")]
pub mod SatisfactionSupplyRewardExp;
#[cfg(feature = "ScenarioTree")]
pub mod ScenarioTree;
#[cfg(feature = "ScenarioTreeTips")]
pub mod ScenarioTreeTips;
#[cfg(feature = "ScenarioTreeTipsClassQuest")]
pub mod ScenarioTreeTipsClassQuest;
#[cfg(feature = "ScenarioType")]
pub mod ScenarioType;
#[cfg(feature = "ScreenImage")]
pub mod ScreenImage;
#[cfg(feature = "SecretRecipeBook")]
pub mod SecretRecipeBook;
#[cfg(feature = "SequentialEvent")]
pub mod SequentialEvent;
#[cfg(feature = "SequentialEventMultipleRange")]
pub mod SequentialEventMultipleRange;
#[cfg(feature = "SharlayanCraftWorks")]
pub mod SharlayanCraftWorks;
#[cfg(feature = "SharlayanCraftWorksSupply")]
pub mod SharlayanCraftWorksSupply;
#[cfg(feature = "ShellFixedFromCommand")]
pub mod ShellFixedFromCommand;
#[cfg(feature = "Skirmish")]
pub mod Skirmish;
#[cfg(feature = "SkyIsland")]
pub mod SkyIsland;
#[cfg(feature = "SkyIsland2")]
pub mod SkyIsland2;
#[cfg(feature = "SkyIsland2Mission")]
pub mod SkyIsland2Mission;
#[cfg(feature = "SkyIsland2MissionDetail")]
pub mod SkyIsland2MissionDetail;
#[cfg(feature = "SkyIsland2MissionType")]
pub mod SkyIsland2MissionType;
#[cfg(feature = "SkyIsland2RangeType")]
pub mod SkyIsland2RangeType;
#[cfg(feature = "SkyIslandMapMarker")]
pub mod SkyIslandMapMarker;
#[cfg(feature = "SkyIslandSubject")]
pub mod SkyIslandSubject;
#[cfg(feature = "Snipe")]
pub mod Snipe;
#[cfg(feature = "SnipeCollision")]
pub mod SnipeCollision;
#[cfg(feature = "SnipeElementId")]
pub mod SnipeElementId;
#[cfg(feature = "SnipeHitEvent")]
pub mod SnipeHitEvent;
#[cfg(feature = "SnipePerformanceCamera")]
pub mod SnipePerformanceCamera;
#[cfg(feature = "SnipeTalk")]
pub mod SnipeTalk;
#[cfg(feature = "SnipeTalkName")]
pub mod SnipeTalkName;
#[cfg(feature = "SpearfishingComboTarget")]
pub mod SpearfishingComboTarget;
#[cfg(feature = "SpearfishingEcology")]
pub mod SpearfishingEcology;
#[cfg(feature = "SpearfishingItem")]
pub mod SpearfishingItem;
#[cfg(feature = "SpearfishingItemReverse")]
pub mod SpearfishingItemReverse;
#[cfg(feature = "SpearfishingNotebook")]
pub mod SpearfishingNotebook;
#[cfg(feature = "SpearfishingRecordPage")]
pub mod SpearfishingRecordPage;
#[cfg(feature = "SpearfishingSilhouette")]
pub mod SpearfishingSilhouette;
#[cfg(feature = "SpecialShop")]
pub mod SpecialShop;
#[cfg(feature = "SpecialShopItemCategory")]
pub mod SpecialShopItemCategory;
#[cfg(feature = "Spectator")]
pub mod Spectator;
#[cfg(feature = "Stain")]
pub mod Stain;
#[cfg(feature = "StainTransient")]
pub mod StainTransient;
#[cfg(feature = "StanceChange")]
pub mod StanceChange;
#[cfg(feature = "Status")]
pub mod Status;
#[cfg(feature = "StatusHitEffect")]
pub mod StatusHitEffect;
#[cfg(feature = "StatusLoopVFX")]
pub mod StatusLoopVFX;
#[cfg(feature = "Story")]
pub mod Story;
#[cfg(feature = "StorySystemDefine")]
pub mod StorySystemDefine;
#[cfg(feature = "SubmarineExploration")]
pub mod SubmarineExploration;
#[cfg(feature = "SubmarineExplorationLog")]
pub mod SubmarineExplorationLog;
#[cfg(feature = "SubmarineMap")]
pub mod SubmarineMap;
#[cfg(feature = "SubmarinePart")]
pub mod SubmarinePart;
#[cfg(feature = "SubmarineRank")]
pub mod SubmarineRank;
#[cfg(feature = "SubmarineSpecCategory")]
pub mod SubmarineSpecCategory;
#[cfg(feature = "SwitchTalk")]
pub mod SwitchTalk;
#[cfg(feature = "SwitchTalkVariation")]
pub mod SwitchTalkVariation;
#[cfg(feature = "SystemGraphicPreset")]
pub mod SystemGraphicPreset;
#[cfg(feature = "TelepoRelay")]
pub mod TelepoRelay;
#[cfg(feature = "TerritoryAethernet")]
pub mod TerritoryAethernet;
#[cfg(feature = "TerritoryAetheryteList")]
pub mod TerritoryAetheryteList;
#[cfg(feature = "TerritoryChatRule")]
pub mod TerritoryChatRule;
#[cfg(feature = "TerritoryIntendedUse")]
pub mod TerritoryIntendedUse;
#[cfg(feature = "TerritoryType")]
pub mod TerritoryType;
#[cfg(feature = "TerritoryTypeTelepo")]
pub mod TerritoryTypeTelepo;
#[cfg(feature = "TerritoryTypeTransient")]
pub mod TerritoryTypeTransient;
#[cfg(feature = "TextCommand")]
pub mod TextCommand;
#[cfg(feature = "TextCommandParam")]
pub mod TextCommandParam;
#[cfg(feature = "TiltParam")]
pub mod TiltParam;
#[cfg(feature = "Title")]
pub mod Title;
#[cfg(feature = "TofuEditParam")]
pub mod TofuEditParam;
#[cfg(feature = "TofuObject")]
pub mod TofuObject;
#[cfg(feature = "TofuObjectCategory")]
pub mod TofuObjectCategory;
#[cfg(feature = "TofuPreset")]
pub mod TofuPreset;
#[cfg(feature = "TofuPresetCategory")]
pub mod TofuPresetCategory;
#[cfg(feature = "TofuPresetObject")]
pub mod TofuPresetObject;
#[cfg(feature = "TomestoneConvert")]
pub mod TomestoneConvert;
#[cfg(feature = "Tomestones")]
pub mod Tomestones;
#[cfg(feature = "TomestonesItem")]
pub mod TomestonesItem;
#[cfg(feature = "TopicSelect")]
pub mod TopicSelect;
#[cfg(feature = "Town")]
pub mod Town;
#[cfg(feature = "TradeScreenImage")]
pub mod TradeScreenImage;
#[cfg(feature = "Trait")]
pub mod Trait;
#[cfg(feature = "TraitRecast")]
pub mod TraitRecast;
#[cfg(feature = "TraitTransient")]
pub mod TraitTransient;
#[cfg(feature = "Transformation")]
pub mod Transformation;
#[cfg(feature = "Treasure")]
pub mod Treasure;
#[cfg(feature = "TreasureHuntRank")]
pub mod TreasureHuntRank;
#[cfg(feature = "TreasureHuntTexture")]
pub mod TreasureHuntTexture;
#[cfg(feature = "TreasureModel")]
pub mod TreasureModel;
#[cfg(feature = "TreasureSpot")]
pub mod TreasureSpot;
#[cfg(feature = "Tribe")]
pub mod Tribe;
#[cfg(feature = "TriggerEffect")]
pub mod TriggerEffect;
#[cfg(feature = "TripleTriad")]
pub mod TripleTriad;
#[cfg(feature = "TripleTriadCard")]
pub mod TripleTriadCard;
#[cfg(feature = "TripleTriadCardObtain")]
pub mod TripleTriadCardObtain;
#[cfg(feature = "TripleTriadCardRarity")]
pub mod TripleTriadCardRarity;
#[cfg(feature = "TripleTriadCardResident")]
pub mod TripleTriadCardResident;
#[cfg(feature = "TripleTriadCardType")]
pub mod TripleTriadCardType;
#[cfg(feature = "TripleTriadCompetition")]
pub mod TripleTriadCompetition;
#[cfg(feature = "TripleTriadDefine")]
pub mod TripleTriadDefine;
#[cfg(feature = "TripleTriadResident")]
pub mod TripleTriadResident;
#[cfg(feature = "TripleTriadRule")]
pub mod TripleTriadRule;
#[cfg(feature = "TripleTriadTournament")]
pub mod TripleTriadTournament;
#[cfg(feature = "Tutorial")]
pub mod Tutorial;
#[cfg(feature = "TutorialDPS")]
pub mod TutorialDPS;
#[cfg(feature = "TutorialGimmick")]
pub mod TutorialGimmick;
#[cfg(feature = "TutorialHealer")]
pub mod TutorialHealer;
#[cfg(feature = "TutorialTank")]
pub mod TutorialTank;
#[cfg(feature = "UDS_Event")]
pub mod UDS_Event;
#[cfg(feature = "UDS_Object")]
pub mod UDS_Object;
#[cfg(feature = "UDS_Property")]
pub mod UDS_Property;
#[cfg(feature = "UDS_Stats")]
pub mod UDS_Stats;
#[cfg(feature = "UIColor")]
pub mod UIColor;
#[cfg(feature = "UIConst")]
pub mod UIConst;
#[cfg(feature = "UILevelLookup")]
pub mod UILevelLookup;
#[cfg(feature = "VFX")]
pub mod VFX;
#[cfg(feature = "VVDData")]
pub mod VVDData;
#[cfg(feature = "VVDNotebookContents")]
pub mod VVDNotebookContents;
#[cfg(feature = "VVDNotebookSeries")]
pub mod VVDNotebookSeries;
#[cfg(feature = "VVDRouteData")]
pub mod VVDRouteData;
#[cfg(feature = "VVDVariantAction")]
pub mod VVDVariantAction;
#[cfg(feature = "Vase")]
pub mod Vase;
#[cfg(feature = "VaseFlower")]
pub mod VaseFlower;
#[cfg(feature = "WKSAchievement")]
pub mod WKSAchievement;
#[cfg(feature = "WKSAchievementDailyDefine")]
pub mod WKSAchievementDailyDefine;
#[cfg(feature = "WKSAchievementRewardItem")]
pub mod WKSAchievementRewardItem;
#[cfg(feature = "WKSCosmoToolClass")]
pub mod WKSCosmoToolClass;
#[cfg(feature = "WKSCosmoToolCommonLevel")]
pub mod WKSCosmoToolCommonLevel;
#[cfg(feature = "WKSCosmoToolDataAmount")]
pub mod WKSCosmoToolDataAmount;
#[cfg(feature = "WKSCosmoToolName")]
pub mod WKSCosmoToolName;
#[cfg(feature = "WKSCosmoToolPassiveBuff")]
pub mod WKSCosmoToolPassiveBuff;
#[cfg(feature = "WKSDevGrade")]
pub mod WKSDevGrade;
#[cfg(feature = "WKSDevGradeBGSet")]
pub mod WKSDevGradeBGSet;
#[cfg(feature = "WKSEmergencyInfo")]
pub mod WKSEmergencyInfo;
#[cfg(feature = "WKSEmergencyInfoText")]
pub mod WKSEmergencyInfoText;
#[cfg(feature = "WKSEmergencyMission")]
pub mod WKSEmergencyMission;
#[cfg(feature = "WKSEmergencyMissionGroup")]
pub mod WKSEmergencyMissionGroup;
#[cfg(feature = "WKSEmergencyProblem")]
pub mod WKSEmergencyProblem;
#[cfg(feature = "WKSFateControl")]
pub mod WKSFateControl;
#[cfg(feature = "WKSFortunePatternUIColorSet")]
pub mod WKSFortunePatternUIColorSet;
#[cfg(feature = "WKSFortunePatternUIPlace")]
pub mod WKSFortunePatternUIPlace;
#[cfg(feature = "WKSFortunePrizeGrade")]
pub mod WKSFortunePrizeGrade;
#[cfg(feature = "WKSFortuneSPPatternUIPlace")]
pub mod WKSFortuneSPPatternUIPlace;
#[cfg(feature = "WKSFunction")]
pub mod WKSFunction;
#[cfg(feature = "WKSItemInfo")]
pub mod WKSItemInfo;
#[cfg(feature = "WKSItemSubCategory")]
pub mod WKSItemSubCategory;
#[cfg(feature = "WKSMechaEventData")]
pub mod WKSMechaEventData;
#[cfg(feature = "WKSMechaEventObject")]
pub mod WKSMechaEventObject;
#[cfg(feature = "WKSMechaEventObjectGroup")]
pub mod WKSMechaEventObjectGroup;
#[cfg(feature = "WKSMechaEventRewardUI")]
pub mod WKSMechaEventRewardUI;
#[cfg(feature = "WKSMechaLivelyActorGroup")]
pub mod WKSMechaLivelyActorGroup;
#[cfg(feature = "WKSMissionInfo")]
pub mod WKSMissionInfo;
#[cfg(feature = "WKSMissionLotterySpecialCond")]
pub mod WKSMissionLotterySpecialCond;
#[cfg(feature = "WKSMissionMapMarker")]
pub mod WKSMissionMapMarker;
#[cfg(feature = "WKSMissionPromotionCondition")]
pub mod WKSMissionPromotionCondition;
#[cfg(feature = "WKSMissionRecipe")]
pub mod WKSMissionRecipe;
#[cfg(feature = "WKSMissionReward")]
pub mod WKSMissionReward;
#[cfg(feature = "WKSMissionSupplyItem")]
pub mod WKSMissionSupplyItem;
#[cfg(feature = "WKSMissionText")]
pub mod WKSMissionText;
#[cfg(feature = "WKSMissionToDo")]
pub mod WKSMissionToDo;
#[cfg(feature = "WKSMissionToDoEvalutionItem")]
pub mod WKSMissionToDoEvalutionItem;
#[cfg(feature = "WKSMissionToDoEvalutionRefin")]
pub mod WKSMissionToDoEvalutionRefin;
#[cfg(feature = "WKSMissionToDoSuccessType")]
pub mod WKSMissionToDoSuccessType;
#[cfg(feature = "WKSMissionUnit")]
pub mod WKSMissionUnit;
#[cfg(feature = "WKSParam")]
pub mod WKSParam;
#[cfg(feature = "WKSPioneeringTrail")]
pub mod WKSPioneeringTrail;
#[cfg(feature = "WKSPioneeringTrailString")]
pub mod WKSPioneeringTrailString;
#[cfg(feature = "WKSPraiseHologram")]
pub mod WKSPraiseHologram;
#[cfg(feature = "WKSScoreList")]
pub mod WKSScoreList;
#[cfg(feature = "WKSSharedGroup")]
pub mod WKSSharedGroup;
#[cfg(feature = "WKSTerritoryInfo")]
pub mod WKSTerritoryInfo;
#[cfg(feature = "WKSText")]
pub mod WKSText;
#[cfg(feature = "WKSZoneFloorCollision")]
pub mod WKSZoneFloorCollision;
#[cfg(feature = "Warp")]
pub mod Warp;
#[cfg(feature = "WarpCondition")]
pub mod WarpCondition;
#[cfg(feature = "WarpLogic")]
pub mod WarpLogic;
#[cfg(feature = "WeaponTimeline")]
pub mod WeaponTimeline;
#[cfg(feature = "Weather")]
pub mod Weather;
#[cfg(feature = "WeatherGroup")]
pub mod WeatherGroup;
#[cfg(feature = "WeatherRate")]
pub mod WeatherRate;
#[cfg(feature = "WeatherReportReplace")]
pub mod WeatherReportReplace;
#[cfg(feature = "WebGuidance")]
pub mod WebGuidance;
#[cfg(feature = "WebURL")]
pub mod WebURL;
#[cfg(feature = "WeddingBGM")]
pub mod WeddingBGM;
#[cfg(feature = "WeddingFlowerColor")]
pub mod WeddingFlowerColor;
#[cfg(feature = "WeddingPlan")]
pub mod WeddingPlan;
#[cfg(feature = "WeeklyBingoOrderData")]
pub mod WeeklyBingoOrderData;
#[cfg(feature = "WeeklyBingoRewardData")]
pub mod WeeklyBingoRewardData;
#[cfg(feature = "WeeklyBingoText")]
pub mod WeeklyBingoText;
#[cfg(feature = "WeeklyLotBonus")]
pub mod WeeklyLotBonus;
#[cfg(feature = "WeeklyLotBonusThreshold")]
pub mod WeeklyLotBonusThreshold;
#[cfg(feature = "World")]
pub mod World;
#[cfg(feature = "WorldDCGroupType")]
pub mod WorldDCGroupType;
#[cfg(feature = "XPVPGroupActivity")]
pub mod XPVPGroupActivity;
#[cfg(feature = "YKW")]
pub mod YKW;
#[cfg(feature = "YardCatalogCategory")]
pub mod YardCatalogCategory;
#[cfg(feature = "YardCatalogItemList")]
pub mod YardCatalogItemList;
#[cfg(feature = "ZoneSharedGroup")]
pub mod ZoneSharedGroup;
#[cfg(feature = "ZoneTimeline")]
pub mod ZoneTimeline;
